# Generated by Django 5.0 on 2023-12-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studenttable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentName', models.CharField(max_length=50)),
                ('Address', models.TextField()),
                ('Age', models.IntegerField()),
                ('Email', models.EmailField(max_length=100)),
                ('JoiningDate', models.DateField()),
                ('Qualification', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=100)),
                ('MobileNumber', models.CharField(max_length=11)),
            ],
        ),
    ]
